### PR TITLE
Add nonce verification and capability checks

### PR DESCRIPTION
**Pull request by timohubois**
Should fix current security issues:

1. [Arbitrary Menu Order Update via CSRF](https://wpscan.com/vulnerability/734064e3-afe9-4dfd-8d76-8a757cc94815)
2. [Subscriber+ Arbitrary Menu Order Update](https://wpscan.com/vulnerability/8f900d37-6eee-4434-8b9b-d10cc4a9167c)

### CODE REVIEW

**Comment by hijiriworld** [comment]
Thank your for your pull request!

**Comment by curtismchale** [comment]
@timohubois  @hijiriworld looking at this in production and the line about `! current_user_can( 'manage_sites' )` means the scripts won't be loaded for anyone if they don't have that permission. This means any user that doesn't have a multisite instance will not be able to use the plugin as the scripts won't load.

We also have the other two capabilities added that span two different roles. So only an admin has both `edit_posts` and `manage_categories` which means editors can't drag/drop anything for posts as they don't also have the `manage_categories` capability by default.

It may even be better to add a capability for `hicpo_organize_posts` and apply that to the editor role.

```php
add_action( 'admin_init', 'add_hicpo_caps' );
function add_hicpo_caps(){
  // gets role
  $editor = get_role( 'editor' );

  $editor->add_cap( 'hicpo_organize_posts' );
}
```

Likely even better to run that with an activation hook on the plugin instead of running it each time as capabilities are persistent.

**Comment by timohubois** [comment]
@curtismchale thanks for your feedback. My target behind was to quickly fix the security issue and bring the plugin back. You are absolutely correct and I made a mistake in relation the `! current_user_can( 'manage_sites' )`. Really like the idea with the custom capability and will also catch it up.

**Comment by curtismchale** [comment]
@timohubois security was also my main thing as I manage 80+ US city sites and we want them to be secure. I appreciate the work.

**Comment by timohubois** [comment]
@curtismchale created a new [pull request](https://github.com/hijiriworld/intuitive-custom-post-order/pull/50) in relation to your suggestion.

**Pull request merged**
